### ISSUE TITLE
How can i send message to other devices connected with the same socket?

### ISSUE THREAD

**Issue by vinita90** [ghedipunk/PHP-Websockets#59] opened 2015-12-04 05:40 UTC
Hello Guys,
This code is working very fine for me, even all android devices also connecting with the socket.
Now i want to send messages to other devices connected with the socket as me.
And also want to send message to individual also.

Can anybody suggest me anything?

**Comment by ghedipunk** [comment] 2015-12-04 18:07
The `WebSocketUser` object is used to keep track of different connections.

In the `send()` method, you need to specify the `WebSocketUser` (or a class that inherits from `WebSocketUser` (in future versions, a class that implements the `WebSocketUser` interface)) of the connection that you want to send the message to.

Closing because this is not a bug, it is a support request.  If you still need additional support, please feel free to reply to this despite it being closed.

**Closed by ghedipunk** 2015-12-04 18:07 UTC

**Comment by vinita90** [comment] 2015-12-08 05:16
Thanks @ghedipunk
