### ISSUE TITLE
deframe fails

### ISSUE THREAD

**Issue by merged-packets** [ghedipunk/PHP-Websockets#22] opened 2015-01-12 02:09 UTC
PHP websocket server cannot correctly deframe websocket messages
if a burst of small messages was sent to the server and some TCP 
packets were merged head-to-tail into bigger TCP packets before
PHP receives packet data 
(http://en.wikipedia.org/wiki/Nagle's_algorithm)

**Comment by ghedipunk** [comment] 2015-01-12 22:59
Looking at the available options without doing any testing yet, it looks like the best way for me to go is to implement TCP_NODELAY first, which will prevent data loss for all cases, then work on a way to parse the merged packets.  

After work on parsing the merged packets, the TCP_NODELAY option will be an opt-in option for applications that really and truly need as little latency as possible, but parsing the merged packets will be default because the vast majority of applications don't need sub-200ms reaction times.

**Comment by merged-packets** [comment] 2015-01-13 02:30
TCP_NODELAY would be a nice to have option.
I would also add SO_KEEPALIVE, if possible.

**Comment by kfchoong** [comment] 2015-01-27 16:08
I am facing the same problem. May I know if a new version will be released?

**Comment by Xaraknid** [comment] 2015-04-04 00:02
I have the same issue.  When from my client I "spam" the server sending multiple socket.send().  I search and found the problem.  The problem is that deframe assume there will be only one frame per packet sending to him. That's not true sending 100 socket.send to the server I end up sending 9 packets who have respectively (5,35,14,9,9,7,8,7,6) frames inside of the packet.

So deframe() is  to deframe the frame not packet.   I made a little function to split packet into frame and send frame to the deframe function and instead of packet. 

I'll pull my code.

**Comment by Xaraknid** [comment] 2015-04-05 09:33
fix an  issue I have with split_packet() typo + now read the right headers for each frame within the packet.

**Comment by ghedipunk** [comment] 2015-04-05 14:43
I'll review, test, and merge as soon as possible.  Hopefully that means a merge today.

**Comment by amb3rl4nn** [comment] 2015-04-05 15:19
I've tested the update made today and it resolves the issue from yesterday where sending certain size packets were getting a header read issue.  It appears to be working correctly.  Also "Length" is still spelled incorrectly.

**Comment by Xaraknid** [comment] 2015-04-05 23:28
Thanks, I fix it in my directory also.  Let me dig a little more into deframe I'll shortly pull modification because I didn't like the fact that I add a function with alot of similarity only change is the args and return value ( calcoffset() and extractPayload() ) also as deframe now process only one frame at time now need a rework.  I will pull something shortly.

**Closed** 2016-01-05 21:46 UTC
